{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "savvy.fullname" . }}
  labels:
    {{- include "savvy.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value }}
globalDefault: false
description: {{ .Values.priorityClass.description | quote }}
{{- if .Values.priorityClass.preemptionPolicy }}
preemptionPolicy: {{ .Values.priorityClass.preemptionPolicy }}
{{- end }}
{{- end }}
