---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-session
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-session
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: savvy-session-secret
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-db
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: savvy-db-password
        property: password
