---
apiVersion: v2
name: savvy
description: A Helm chart for Savvy - Digital Cards, Vouchers & Gift Cards Management
type: application
version: 1.1.0
appVersion: "1.1.0"
home: https://github.com/sbaerlocher/savvy
maintainers:
  - name: Simon BÃ¤rlocher
    email: s.baerlocher@sbaerlocher.ch
keywords:
  - savvy
  - loyalty
  - cards
  - vouchers
  - gift-cards
  - pwa
sources:
  - https://github.com/sbaerlocher/savvy
icon: https://raw.githubusercontent.com/sbaerlocher/savvy/main/static/icons/icon-512x512.png
