---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: savvy-production

namespace: savvy

resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml
  - servicemonitor.yaml
  - oauth-configmap.yaml
  - oauth-externalsecret.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: ghcr.io/sbaerlocher/savvy
    newTag: 1.1.0

replicas:
  - name: savvy
    count: 3

labels:
  - pairs:
      environment: production
