apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: savvy-oauth
  labels:
    app.kubernetes.io/name: savvy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: savvy-oauth
    creationPolicy: Owner
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: savvy-oauth-secret
        property: password
