apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: savvy
  labels:
    app.kubernetes.io/name: savvy
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: savvy
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
