---
apiVersion: v1
kind: ConfigMap
metadata:
  name: savvy
data:
  GO_ENV: "development"
  DATABASE_URL: "postgres://savvy:devpassword@dev-postgres:5432/savvy_dev?sslmode=disable"
  ENABLE_LOCAL_LOGIN: "true"
  ENABLE_REGISTRATION: "true"
  OTEL_ENABLED: "false"
