apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: savvy
  labels:
    app.kubernetes.io/name: savvy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: savvy-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-savvy
                port:
                  number: 80
  tls:
    - secretName: savvy-dev-tls
      hosts:
        - savvy-dev.local
